#!/usr/bin/env bash
#installs an nginx web server

# Install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Ensure nginx is listening on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Create a simple HTML file with "Hello World!"
echo "Hello World!" > /var/www/html/index.nginx-debian.html
index.nginx-debian.html


# Restart nginx (without using systemctl)
service nginx start