#!/usr/bin/env bash
#displays a list of currently running processes

# Use the ps command to get information about processes
# -e option: Select all processes
# -o option: Specify the output format

ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest