#!/usr/bin/env bash
#displays a list of currently running processes containing the bash word.
# shellcheck disable=SC2009
ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command | grep 'bash'
