#!/usr/bin/env bash
# Display PID and process name of processes containing the word 'bash'

# Use pgrep to find process IDs for 'bash'
# Loop through the PIDs and display the PID and process name

for pid in $(pgrep bash); do
    cmdline_with_spaces=$(tr '\0' ' ' < "/proc/$pid/cmdline")
    process_name=$(echo "$cmdline_with_spaces" | awk '{print $1}')

    echo "$pid $process_name"
done
