#!/usr/bin/env bash
#Displays a formatted content of the current working directory

for file in *; do
    if [[ ! $file =~ ^/. ]]; then
        format_ls=$(echo $file | cut -d '-' -f 2-)
        echo "$format_ls"
    fi
done
