#!/usr/bin/env bash
# Script that configures the nginx file with sed

# Set the nginx user in nginx.conf
sed -i 's/user\s\+[^;]\+/user nginx;/' /etc/nginx/nginx.conf

# Modify the default server block to listen on all IPs on port 8080
sed -i 's/listen\s\+80\s\+default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart
