#!/usr/bin/env bash
# Script that configures the nginx file with sed
chmod 777 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
service nginx restart
